### ISSUE TITLE
What is src/android/cordova-generic-ad.jar?

### ISSUE THREAD

**Issue by letmaik** [floatinghotpot/cordova-extension#12]
There's a jar file (src/android/cordova-generic-ad.jar) in this plugin without corresponding source code, at least I couldn't find it. And this is used in the cordova-admob-pro plugin for example. Two questions:
1. Why is there a jar file in the repo and not the .java files?
2. Why is there ad-related stuff in this plugin? It seems out of scope from what it says in the README.

**Comment by floatinghotpot** [comment]
it's a library defines common API implemented by all rjfun ad plugins, including admob, flurry, facebookads, etc. it's closed source as it has code for license control purpose.

**Comment by letmaik** [comment]
Well, your approach seems to be security by obscurity which is not secure at all. There are many Java bytecode decompilers that can reconstruct the source code of .class files to some degree.
Apart from that, I now don't feel comfortable using any of your plugins as I have no idea what your hidden code is actually doing. In theory there could be a back door in it that could allow you to control all phones that have your plugins deployed on them. Only having the code available would give me confidence.
Your plugins are great, but please, find a different solution that is open.

**Comment by floatinghotpot** [comment]
Try this one, if you prefer fully open source:
https://github.com/floatinghotpot/cordova-plugin-admob

**Comment by letmaik** [comment]
I checked your closed source code via http://www.javadecompilers.com and found that it has functionality to execute arbitrary JavaScript code that is loaded from your license server at http://adlic.rjfun.com/adlic. This by itself opens a massive potential backdoor which is not described in your license conditions. Any comment?
