### ISSUE TITLE
"libCordovaGenericAd.a(GenericAdPlugin.o) does not contain bitcode"

### ISSUE THREAD

**Issue by grgarside** [floatinghotpot/cordova-extension#3]
Upon attempting to build an app with this plugin for iOS 9 with bitcode enabled, the build fails with the following error:

> ld: '*/path/to/appname*/platforms/ios/*appname*/Plugins/cordova-plugin-extension/libCordovaGenericAd.a(GenericAdPlugin.o)' does not contain bitcode.  
You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

I can build my app fine without bitcode if I disable bitcode for my app entirely, but can bitcode be added so that I can enable it for my app?

**Comment by floatinghotpot** [comment]
will find time to update it.

**Comment by studio31** [comment]
+1

**Comment by bAstimc** [comment]
+1

**Comment by RafalWilinski** [comment]
+1
