### ISSUE TITLE
armv7 build error

### ISSUE THREAD

**Issue by balicekt** [floatinghotpot/cordova-extension#6]
Hey, I just wanted to try ionic app in iphone 6 device. In simulator everything works just fine. I'm using cordova plugin cordova-plugin-admobpro and there is dependency to cordova-plugin-extension.

my CLI commands: 
ionic star testIOS tabs
cd testIOS
ionic plugin add cordova-plugin-extension
ionic run ios --device

I will get this error: 
** BUILD FAILED **

The following build commands failed:
Ld build/device/testIOS.app/testIOS normal armv7
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/balicekt/Documents/Projects/GAME/testIOS/platforms/ios/cordova/build-debug.xcconfig,-project,testIOS.xcodeproj,ARCHS=armv7 armv7s arm64,-target,testIOS,-configuration,Debug,-sdk,iphoneos,build,VALID_ARCHS=armv7 armv7s arm64,CONFIGURATION_BUILD_DIR=/Users/balicekt/Documents/Projects/GAME/testIOS/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/balicekt/Documents/Projects/GAME/testIOS/platforms/ios/build/sharedpch

Could anyonw help me? I have no idea what could I do with it.

**Comment by floatinghotpot** [comment]
which version of Xcode and iOS do you test with?

**Comment by balicekt** [comment]
iOS 9 and Xcode 7.0.1. But after hours I finally found a solution! It was because of a bit code. I had to open .xcodeproj file and set in Build Settings -> Enable Bitcode -> NO

**Comment by floatinghotpot** [comment]
Yes, you are correct. Will fix this later.

**Comment by balicekt** [comment]
Ok thank you. Can I leave this issue open and after fix this you will close it?

**Comment by floatinghotpot** [comment]
Okay.
